import { AccordionComponent } from "../../components/accordion";

const data = {
  mcs: {
    title: "Master of Computer Science",
    "Program/MQR No.":
      "Master of Computer Science – Research\nMQR Code: MQA/FA6585",
    "Brief introduction":
      "The Master of Computer Science (By Research) programme is offered by the Department of Computer Science in 2011. The programme is designed to enhance knowledge and impart technical competencies to postgraduate students on issues pertaining to Computer Science area. Graduates from this programme are expected to:\n\na)	Show a high-level of understanding in Computer Science theories and applications. This understanding must transcend the implementation details of the various components to encompass an appreciation for the structure of computer systems and the processes involved in construction and analysis.\nb)	Appreciate the interplay between theory and practice. Graduates from this programme will be able to understand the theoretical underpinning of Computer Science discipline as well as how they are applied in practical applications.\nc)	Display characteristics of Muslim scientist who are technically competent, pious and ready to serve the Ummah",
    "Program Outcome":
      "1.	Apply and integrate knowledge concerning current research issues in computing and produce work that is at the forefront of developments in the domain of the programme of study;\n2.	Evaluate and analyse computing solutions in terms of their usability, efficiency and effectiveness;\n3.	Develop computing solutions and use necessary tools to analyse their performance;\n4.	Apply existing techniques of research and enquiry to acquire, interpret and extend;\n5.	Knowledge in computing;\n6.	Communicate and function effectively in a group;\n7.	Prepare, publish and present technical material to a diverse audience; and\n8.	Demonstrate behaviour that is consistent with codes of professional ethics and responsibility.",
    "Career Opportunities":
      "There is a high demand from employers for computer science graduates from a wide variety of organizations government and private sectors. Graduates can position themselves in a large number of exciting fields of works. Some of positions are as follows:\n•    System Developer\n•    Computer Analyst\n•    Software Engineer\n•    Data Scientist\n•    Database Developer\n•    Network System Administrator\n•    Wireless Systems Designer\n•    Information Security Analyst\n•    Computer Forensic Analyst\n•    Network Engineer\n•    Academician\n•    Researcher in Computer Science",
    "Program Structure":
      "In the first semester, a student is required to audit two (2) Kulliyyah required courses: ICT Research Methods and Islamic Worldview on ICT and Society. Within six (6) months from the registration date, the students are required to submit his/her research synopsis proposal which need to be defended. Students are also required to present their research progress at a formal PG colloquium at different stages of research. Finally, the student shall defend his/her research in a viva voce and made revisions in accordance with the examiner’s reports.",
    "Areas of Research":
      "Artificial Intelligence, Soft Computing, Database Systems, Big Data, Data Science, Cryptography, Software Engineering, Computer Security, Computer Network and Distributed Systems, Quantum Computing, Cognitive Science, Knowledge Management, Ubiquitous Computer, and Algorithms and Theory.",
    "Duration of Study":
      "The programme is offered via full time and also part time mode. The full time programme would normally require two (2) years (4 semesters) study duration and the maximum duration allowed is 3 years (6 semesters).\n\nThe part time programme would normally require four (4) years (8 semesters). The maximum period allowed for the completion of the programme is 5 years (10 semesters) for part time study.",
  },
  dcs: {
    title: "Doctor of Philosophy (Computer Science) – Research",
    "Program/MQR No.":
      "Doctor of Philosophy (Computer Science) – Research MQR Code: MQA/FA6589",
    "Brief introduction":
      "The Doctor of Philosophy (Computer Science) by Research programme is offered by the Department of Computer Science in 2011. The programme is designed to enhance knowledge and impart technical competencies to postgraduate students on issue pertaining to Computer Science area. Graduates from this programme are expected to: a)	Show a high-level of understanding in Computer Science theories and applications. This understanding must transcend the implementation details of the various components to encompass an appreciation for the structure of computer systems and the processes involved in construction and analysis. b)	Appreciate the interplay between theory and practice. Graduates from this programme will be able to understand the theoretical underpinning of Computer Science discipline as well as how they are applied in practical applications.c)	Display characteristics of Muslim scientist who are technically competent, pious and ready to serve the Ummah.",
    "Program Outcome":
      "1.	Demonstrate a systematic comprehension and in-depth understanding of a discipline and mastery of skills and research methods related to the field of computing;2.	Critically analyse, evaluate and synthesise new and complex ideas; 3.	 Show scholarly capabilities to generate, design, implement and adopt the integral part of the research process based on the computing theoretical framework; 4.	 Contribute to original research that broadens the boundary of knowledge through an in-depth thesis, which has been presented and defended according to International standards including writing in Internationally refereed publications; 5.	 Communicate to peers, scholarly communities and society at large through the preparation, publication and presentation of technical material; 6.	 Promote the technological, social and cultural progress in a knowledge-based society in both academic and professional contexts; 7.	 Demonstrate behaviour that is consistent with codes of professional ethics, legal requirements and responsibility; and 8.	Supervise research projects.",
    "Career Opportunities":
      "There is a high demand from employers for computer science graduates from a wide variety of organizations government and private sectors. Graduates can position themselves in a large number of exciting fields of works. Some of positions are as follows: •    System Developer •    Computer Analyst •    Data Scientist •    Database Developer •    Software Engineer •    Network System Administrator •    Wireless Systems Designer •    Information Security Analyst •    Computer Forensic Analyst •    Network Engineer •    Academician •    Researcher in Computer Science",
    "Program Structure":
      "In the first semester, a student is required to audit two (2) Kulliyyah required courses: ICT Research Methods and Islamic Worldview on ICT and Society. Within six (6) months from the registration date, students are required to submit his/her research synopsis proposal which need to be defended. Pre-requisites for the defence proposal are (1) to attend the PG seminar that will be held once every fortnight in the semester at least two times, and (2) Do a presentation in this seminar at least once. Upon approval, the student will continue his/her research. The final thesis needs to be submitted at the end of the study period. There will be at least two (2) examiners to evaluate the final thesis, one of whom must be from other than IIUM. The appointment of all examiners shall be recommended by the Kulliyyah Postgraduate Committee (KPGC) and endorsed by the University’s Senate. An oral defence of the thesis will be arranged once agreed by the examiners.",
    "Areas of Research":
      "Artificial Intelligence, Soft Computing, Database Systems, Big Data, Data Science, Cryptography, Software Engineering, Computer Security, Computer Network and Distributed Systems, Quantum Computing, Cognitive Science, Knowledge Management, Ubiquitous Computer, and Algorithms and Theory.",
    "Duration of Study":
      "This programme is offered via full time and part time mode. The full time programme would normally require three (3) years (6 semesters) study duration and the maximum duration allowed is 6 years (12 semesters).  The part time programme would normally require six (6) years (12 semesters) to the maximum of 8 years (16 semesters).",
  },
  mlis: {
    title: "Master of Library and Information Science",
    "Program/MQR No.":
      "Master of Library and Information Science – By Mixed-Mode\nMQR Code: MQA/FA6583",
    "Brief introduction":
      "Master of Library and Information Science is offered by the Department of Library and Information Science, KICT.\n\nThe Master of Library and Information Science aims at fulfilling the demands of libraries and information industries that require a strong background in information management as well as a substantial amount of “hands on” experience in the related field. The programme covers a range of topics in information management, including information retrieval, acquisition and processing.",
    "Program Outcome":
      "1.	Knowledge – Demonstrate creative and innovative ideas with established knowledge in the field of library and information science and awareness of current development therein.\n2.	Practical Skills – Use relevant ICT skills and knowledge learnt in library and information science for professional and personal development.\n3.	Social skills and Responsibilities – Cooperate with others and apply knowledge in a socially responsible manner for the progress of the nation and the ummah.\n4.	Value, Attitudes and Professionalism – Demonstrate commitment to ethics, autonomy and professionalism in the workplace and everyday life.\n5.	Communication, Leadership and Team Skills – Communicate with people from a diverse range of backgrounds with empathy, showing leadership qualities and group work working spirit.\n6.	Problem Solving and Scientific Skills – Critically analyze issues and demonstrate skillfulness in planning, design and managing design strategies.\n7.	Information Management and Lifelong Learning Skills – Use the necessary learning skills in information management and apply effective strategies for lifelong self-improvement.\n8.	Managerial and Entrepreneurial Skills – Apply managerial and entrepreneurial skills in relevant fields.\n9.	Integration of Islamic Revealed Knowledge and Values – Use Islamic principles to analyze and evaluate ideas and theories in modern disciplines.",
    "Career Opportunities":
      "The Master of Library and Information Science aims to strengthen the professionals knowledge and competencies needed for middle and higher level career in various libraries and resource centres in both public and corporate sectors which range from traditional library management courses to the application of technologies in the libraries and information services.\n\n•    Librarian\n•    Knowledge Manager\n•    Information Scientist\n•    Document Manager\n•    Information Broker\n•    Indexer and Abstractor\n•    Web Content Developer\n•    Information Strategist\n•    Information Consultant\n•    Academician",
    "Program Structure":
      "Graduate in Master of Information Technology by coursework, mixed-mode and research shall graduate with 40 credit hours. \ni.	Master of Library and Information Science by Mixed-Mode\nIn the first semester, student is required to complete 2 Kulliyyah required courses: ICT Research Methods and Islamic Worldview on ICT and Society. Students are required to complete five (5) Department core courses (15 credits): Information Sources & Services, Management of Information Institutions, Information Analysis & Organizational I, Information Analysis & Organizational II and Application of IT in Library. Student has to register one (1) elective course (3 credit hours), Fieldworks (4 credit hours) and lastly, students have to complete a Dissertation (12 credit hours).\n1. MLIS by Course Work & Research.pdf\nii.	Master of Library and Information Science by Coursework\nIn the first semester, student is required to complete 2 Kulliyyah required courses: ICT Research Methods and Islamic Worldview on ICT and Society. Students are required to complete five (5) department core courses (15 credits): Information Sources & Services, Management of Information Institutions, Information Analysis & Organizational I, Information Analysis & Organizational II and Application of IT in Library. Student has to register four (4) elective courses (12 credit hours), Fieldworks (4 credit hours) and lastly, students have to register Directed Research Practicum (3 credit hours). \n1. MLIS by Course Work.pdf",
    "Areas of Research":
      "Digital Libraries, Information Retrieval, Information Literacy Skills, Bibliometrics, Database Management, Design and Delivery of Information Services, Library Information System, Organization of Information, Staff Training, Bibliographic Control and Metadata, Indexing and Abstracting, User Behavior in ICT Use, Informatics, and Knowledge Management.",
    "Duration of Study":
      "This program is offered via full time and also part time mode. The full time programme would normally require two (2) years (4 semesters) study duration and the maximum duration allowed is three (3) years (6 semesters).\n\nThe part time programme would normally require four (4) years (8 semesters). The maximum period allowed for the completion of the program is 5 years (10 semesters).",
  },
};

export const Departments = ({ title }) => {
  return <AccordionComponent title={data[title].title} content={data[title]} />;
};
